name: Docker Image CI Test

on:
  push:
    branches-ignore: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    environment: omnicoder-test

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
